version: '3'               #このdocker-compose.ymlファイルの"書式"のバージョン
services:                  #サービスについて定義する。
  nginx:                   #nginxについて定義するという宣言。
    build: ./nginx         #Dockerfileのパス
    image: app:0.0.2       #イメージ名を指定
    container_name: "app"  #コンテナ名を指定
    ports:                 #ポート公開内容を指定する。
      - "8080:80"          #コンテナ側で80だとホスト側で8080となる。
    # volumes:               #ホストのフォルダをコンテナに追加する。 ホスト側:コンテナ側
    #   - ./nginx/conf/default.conf:/etc/nginx/conf.d/default.conf  #コンフィグファイルをコピー
    #   - ./nginx/kuizy:/usr/share/nginx/html         #ソースをコピー
    depends_on:
            - php-fpm

  php-fpm:
        build: ./php-fpm
            # context: ./php-fpm
            # args:
            #     - PHP_VERSION=${PHP_VERSION}
        # volumes:
        #     - ./php-fpm/php.ini:/usr/local/php-fpm/php.ini
        #     - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
        # これ消したらエラー起こさずに php version 8.0.13開けた
        expose:
            - "9000"
        depends_on:
            - db
 
  db:
    image: mysql:5.7
    ports:
      - 13306:3306
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: quizy
      MYSQL_USER: mysql        # 作業ユーザー名→上記データベースの捜査権限をもつ
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassward

  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin:latest
  #   ports:
  #     - 8888:80
  #   depends_on:
  #     - db